# Generated by Django 6.0 on 2026-01-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0007_tag_alter_review_unique_together_dish_tags_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='prepare_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='restaurant_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='restaurant_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
