# Generated by Django 6.0 on 2026-01-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_dish_image_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(help_text='Giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('preparation_time', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurant.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
