# Generated by Django 6.0 on 2026-01-06 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_order_dish_dish_preparation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('preparation_time', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UNKNOWN', 'Chưa xác định'), ('CASH', 'Tiền mặt'), ('PAYPAL', 'PayPal'), ('MOMO', 'MoMo'), ('ZALO', 'ZaloPay')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã đặt bàn'), ('SEATED', 'Khách đang ăn'), ('COMPLETED', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table'),
        ),
    ]
