"""
Django settings for restaurantapis project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/restaurant/static/' % BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mi3idmiag(mxqp5g2&o!zh2m31x+y-3u#ley1cd9@1q00k$w%v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restaurant.apps.RestaurantConfig',
    'drf_yasg',
    'ckeditor',
    'rest_framework',
    'oauth2_provider',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication',)
}

import cloudinary.api
cloudinary.config(cloud_name='dgpiotsmt',
                    api_key='641336261286631',
                    api_secret='9IM8MLY8s6Y4Pj6deAJZv6_FhJU')

CKEDITOR_UPLOAD_PATH = "images/ckeditors/"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurantapis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurantapis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'restaurant',
        'USER': 'root',
        'PASSWORD': 'Nghia2005',
        'HOST': 'localhost'
    }
}

import pymysql
pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'restaurant.User'

import MySQLdb

if not hasattr(MySQLdb, 'version_info'):
    setattr(MySQLdb, 'version_info', (2, 2, 1, 'final', 0))
elif MySQLdb.version_info < (2, 2, 1):
    setattr(MySQLdb, 'version_info', (2, 2, 1, 'final', 0))

CLIENT_ID='fiv9KML4DDALzE24uLSRgE7wkWKxGH7ebOLYfVVz'
CLIENT_SECRET='LLgrI5PnIsbkC3WEKb5er4M0ofO0uQO3BWcm9GSOPKCNPv2HETeJGH42WJozZdCxw3CYXjMN4PadDL0Cuk7YVzInXJaFYZ40MBnV9h9aPgUwwL3oN8Hr6Y36xkuOZC5p'

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

JAZZMIN_SETTINGS = {
    "site_title": "Quản Lý Nhà Hàng",

    "site_header": "Hệ Thống Nhà Hàng",

    "site_brand": "Restaurant Admin",

    "welcome_sign": "Chào mừng",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "restaurant.Category": "fas fa-list",
        "restaurant.Dish": "fas fa-utensils",
        "restaurant.Order": "fas fa-receipt",
        "restaurant.Review": "fas fa-star",
        "restaurant.Tag" : "fas fa-list",
    },

    "show_ui_builder": True,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]